---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: podinfo
  namespace: flux-system
spec:
  digestReflectionPolicy: Always
  imageRepositoryRef:
    name: podinfo
  interval: 1m0s
  policy:
    semver:
      range: 5.0.x
